### ISSUE TITLE
Brightness slider control is inverted

### ISSUE THREAD

**Issue by guidelfrate** [RastislavMirek/FlexColorPicker#1]
Hi! The brightness slider control is actually inverted (from brighter to darker). The control shows brighter as 0% and darker as 100%. 

There is anyway to use this control as a default brightness control, from 0% (dark) to 100% (bright)?

Thanks in advance!

**Comment by RastislavMirek** [comment]
Hi, this is intentional, most users will expect it this way.

Fortunatelly, the library is very flexible so you can build you own "normal brigthnes slider" to use with color picker in 5 minutes. This should be it:

``` swift
struct NormalBrightnessSliderDelegate: ColorSliderDelegate {
    func modifiedColor(from color: HSBColor, with value: CGFloat) -> HSBColor {
        return color.withBrightness(value)
    }

    func valueAndGradient(for color: HSBColor) -> (value: CGFloat, gradientStart: UIColor, gradientEnd: UIColor) {
        return (color.brightness, color.withBrightness(0).toUIColor(), color.withBrightness(1).toUIColor())
    }
}

class NormalBrightnessSliderControl: ColorSliderControl {
    public override func commonInit() {
        sliderDelegate = NormalBrightnessSliderDelegate()
        super.commonInit()
    }
}
// or you can do yourExistingBrightnessSlider.sliderDelegate = NormalBrightnessSliderDelegate()
```
Guide on how to add your new `NormalBrightnessSliderControl` to color picker is in [the readme](https://github.com/RastislavMirek/FlexColorPicker). It's super simple and can be done in storboard as well.

If you like the solution, please star the repo. Also, if you feel this should be default option for `DefaultColorPickerViewController` feel free to add it and send pull request.
