### ISSUE TITLE
Is it me or is does brightness work backwards?

### ISSUE THREAD

**Issue by rauls4** [RastislavMirek/FlexColorPicker#29]
To the leftmost we get 0% brightness, but it's pure white, to the rightmost we get 100% brightness but it's black.

Am I missing something?

**Comment by RastislavMirek** [comment]
Thank you for your report. The thing is: Whatever direction is used people will report it as a bug... It looks like the current behaviour (white on left, black on right) is expected by most people (for some reason). However, I shall fix the percentage, which should be reversed in this particular slider.

**Comment by RastislavMirek** [comment]
Fixed in 1.4.3 in following way: There is new `reversePercentage` property on `ColorSliderControl` and another new property `reverseBrightnessPercentage` on `DefaultColorPickerViewController`. Both are `false` by default to support what most users expect. Just set one of them to `true` (possible from storyboard) to get the behaviour you requested.

**Comment by rauls4** [comment]
Thanks Rastislav, you are faster than most commercial developers!

**Comment by RastislavMirek** [comment]
Why, I am a commercial developer :D Just this project is not... Still, it is used by one commercial app of mine.
Thank you, this was a good catch.
